import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import FixedNavbar from '@/components/fixed navbar/FixedNavbar'
import LgNavbar from '@/components/lg navbar/LgNavbar'
import BottomNavbar from '@/components/bottom navbar/BottomNavbar'
import Footer from '@/components/footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <FixedNavbar />
        <Navbar />
        {children}
        <Footer />
        <BottomNavbar />
      </body>
    </html>
  )
}
